### ISSUE TITLE
Rename Sheet Metal WB from 'My Commands' to 'Sheet Metal' 

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#116]
https://forum.freecadweb.org/viewtopic.php?p=375364#p375364

**Comment by shaise** [comment]
Correct. Fixed.

**Comment by luzpaz** [comment]
@shaise awesome. FYI, not sure if you know this already but if you write `Closes #116` in the git summary when merged in GitHub it will automatically close that issue.

**Comment by shaise** [comment]
@luzpaz  Good to know...
