### ISSUE TITLE
add animated gif to README 

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#12]
would love to see an example of this WBs capabilities quickly. Please add something like this. Thanks!

**Comment by shaise** [comment]
What do you mean by animated gif?

**Comment by luzpaz** [comment]
a gif that has many gifs embedded that play in sequence to simulate a video.   
For example:   
![Part Design Revolution](https://2.bp.blogspot.com/-lwBJamnY518/VvQ4DlPOxRI/AAAAAAAACwY/RBwjZfyW6lYVSFrn5rnw4yhOgnavcietg/s1600/revolution.gif)

**Comment by shaise** [comment]
Can you suggest a software to generate it?

**Comment by easyw** [comment]
https://getsharex.com/ for windows
https://github.com/phw/peek linux
http://www.omgubuntu.co.uk/2016/12/gifine-animated-gif-recorder-linux linux
https://itsfoss.com/best-gif-recorder-linux/

**Comment by shaise** [comment]
easyw, Thanks for the great tools!
luzpaz, Thanks, done.
