### ISSUE TITLE
SheetMetal isn't represented in the FreeCAD dropdown when Workbench is loaded.

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#129]
Most workbenches, once they are loaded, will insert a dropdown in to the FC main dropdown menu between **Macro** and **Windows** of their own workbench commands. SheetMetal doesn't do this. 
Sketcher adds **Sketch**  
TechDraw adds **TechDraw**  etc... 
Lets consider adding this for folks who want to access the SheetMetal commands via the dropdown

**Comment by shaise** [comment]
Is there any doc or example how to do it?

**Comment by luzpaz** [comment]
CC @carlopav  
With all you work on Draft WB, can you illuminate where the code for adding commands to the FC dropdown menu is (as an exmaple) ? Thanks in advance! :smiley:

**Comment by carlopav** [comment]
it's very easy, just try to decomment this line!
https://github.com/shaise/FreeCAD_SheetMetal/blob/d6a33ed3a40ca5f4a71a70093eac428b267da548/InitGui.py#L58

Edit: Probably you are also interested in changing the menu name :)

**Comment by carlopav** [comment]
@luzpaz I still have the doubt if this was what you were asking :)

**Comment by shaise** [comment]
Well, this was rather easy... 
And yes, this is what @luzpaz meant. Thanks @carlopav!

**Comment by carlopav** [comment]
:D

**Comment by shaise** [comment]
It was slightly more complicated on the Fasteners WB, but added it there as well.

**Comment by luzpaz** [comment]
Perfect. Thank you both! :smile:  
Closing ticket
