### ISSUE TITLE
Please add 'topics' aka tags to this repo

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#13]
to facilitate better searching for users, if you don't mind please add: 'freecad' 'addon' and any other tags you deem relevant? Thanks!

**Comment by shaise** [comment]
Hi Luzpaz,
This addon is already supported in freecad's addon manager (0.17)

**Comment by shaise** [comment]
Anyways, added topics. Thanks for the idea.
