### ISSUE TITLE
Unfold exception occur

### ISSUE THREAD

**Issue by karlnik** [shaise/FreeCAD_SheetMetal#140]
Unfold for this file [Unfold fail.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/5063381/Unfold.fail.zip) fail with an exception. Remove the last added bend and it will be OK.

`16:18:06  exception at line 2876('list indices must be integers or slices, not NoneType',)
16:18:06  ('list indices must be integers or slices, not NoneType',)
16:18:06  Traceback (most recent call last):
16:18:06    File "/home/karlnick/.FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 2876, in accept
    s, foldComp, norm, thename, err_cd, fSel, obN  = getUnfold(k_factor_lookup)
16:18:06    File "/home/karlnick/.FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 2174, in getUnfold
    TheTree.Bend_analysis(f_number, None) # traverses the shape and builds the tree-structure
16:18:06    File "/home/karlnick/.FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 1329, in Bend_analysis
    self.Bend_analysis(child_info[0], t_node, child_info[1])
16:18:06    File "/home/karlnick/.FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 1329, in Bend_analysis
    self.Bend_analysis(child_info[0], t_node, child_info[1])
16:18:06    File "/home/karlnick/.FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 1329, in Bend_analysis
    self.Bend_analysis(child_info[0], t_node, child_info[1])
16:18:06    [Previous line repeated 3 more times]
16:18:06    File "/home/karlnick/.FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 1320, in Bend_analysis
    t_node = self.make_new_face_node(face_idx, parent_node, parent_edge, wires_edge_lists)
16:18:06    File "/home/karlnick/.FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 1103, in make_new_face_node
    oppVertIndexes = range(len(self.__Shape.Faces[newNode.c_face_idx].Vertexes))
16:18:06  TypeError: list indices must be integers or slices, not NoneType
16:18:06  `

**Comment by lilaL** [comment]
![image](https://user-images.githubusercontent.com/12436228/99453240-f28fbd80-2924-11eb-8e49-e8f30bf33bdf.png)
There is an error in the whole thing I guess.. I mean how should the unfold looks like?

**Comment by karlnik** [comment]
Checking again it look OK here
![Skärmbild från 2020-11-22 14-21-46](https://user-images.githubusercontent.com/59029207/99905116-03e31c00-2ccf-11eb-8168-086a0b06242f.png)

**Comment by lilaL** [comment]
Did you recompute the model? I get a few reference errors when recomputing it. I would recommend to just remake the model and see if it works out. 
```
21:02:06  <App> PropertyLinks.cpp(390): Unfold_fail#Bend014.baseObject auto change element reference Unfold_fail#Extend003 Face1 -> Face22
21:02:09  <App> PropertyLinks.cpp(390): Unfold_fail#Bend016.baseObject auto change element reference Unfold_fail#Bend015 Face35 -> Face31
21:02:15  <App> PropertyLinks.cpp(390): Unfold_fail#Bend019.baseObject auto change element reference Unfold_fail#Bend018 Face45 -> Face64
```

**Comment by luzpaz** [comment]
@nik570 bump

**Comment by karlnik** [comment]
git pull to the latest version. It did not unfold original file I sent but adding the last failing bend again on part an it unfold so something must have been fixed.

I could see there was changes to bot unfold and other files. Maybe I should press the close with comment button?

**Comment by luzpaz** [comment]
> It did not unfold original file I sent  

Why?

**Comment by luzpaz** [comment]
bump @nik570

**Comment by luzpaz** [comment]
close ticket?

**Comment by luzpaz** [comment]
@shaise probably can be closed

**Comment by shaise** [comment]
closing.
