### ISSUE TITLE
miter angle function broken

### ISSUE THREAD

**Issue by easyw** [shaise/FreeCAD_SheetMetal#141]
@shaise 
the miterangles are available in the bend, but the values don't affect the result.

The issue is described at the FC forum, with a FC file as sample
https://forum.freecadweb.org/viewtopic.php?f=3&t=11303&p=427693#p427663

**Comment by shaise** [comment]
we need to ping @jaisekjames  for that

**Comment by easyw** [comment]
@shaise @jaisekjames 
it seems I missed to enable automiter=false as pointed out here:
https://forum.freecadweb.org/viewtopic.php?p=428118#p428118
Thanks, I'm closing it.
(PS we would need to add this on the wiki...)

**Comment by shaise** [comment]
or perhaps aoutomiter should be false by default?

**Comment by easyw** [comment]
> or perhaps aoutomiter should be false by default?

@shaise :+1:
