### ISSUE TITLE
Wrong sheet metal generation from "sheetmetal wall from sketch" feature.

### ISSUE THREAD

**Issue by dham-eng** [shaise/FreeCAD_SheetMetal#143]
Hello,

I often find myself trying to heal these sheet metal features.

Sometimes it work as intended, sometimes, it does not.

Please note that I tested this command inside and outside PartDesign's Bodies, inside and outside Draft's layers, also.

![image](https://user-images.githubusercontent.com/16336129/94190043-8d19d600-fe79-11ea-9937-bc762e701956.png)
![image](https://user-images.githubusercontent.com/16336129/94190952-cd2d8880-fe7a-11ea-9dd8-b207f2575a02.png)

Workbench is fully updated.

I noticed that one way to trigger this is to modify the base sketch after the sheetmetal wall is created. Sometimes deleting and recreating the wall the problem is gone, sometimes it happens right again.

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22411 (Git)
Build type: Release
Branch: master
Hash: d4519d5aec15bc08f029da5ed15410a494b57b2c
Python version: 3.8.5
Qt version: 5.12.6
Coin version: 4.0.0
OCC version: 7.4.0
Locale: Portuguese/Brazil (pt_BR)

**Comment by jaisekjames** [comment]
is this issue still there. pls send any problematic file or step to produce.

**Comment by dham-eng** [comment]
Hello, jaisekjames,

sorry for the late response.

I tested the updated workbench on a new file and it worked fine.

On the file I showed initially when I try to recalculate it shows "name 'obj' is not defined".

When deleting and recreating the basebend on the same body the length got scaled by a factor of 1000 ( you need to use 1.200mm to get 1200mm of real extrusion). (File attached, you can try this)

When creating a basebend on another body but with sketch being moved in space it gives the error "there are no suitable edges for chamfer or filet". On the other hand, moving a body with a internal basebend works fine.

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23141 (Git)
Build type: Release
Branch: master
Hash: 0eba78d40096720f7a637a9a73c382a08b820bca
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: Portuguese/Brazil (pt_BR)

![WrongExtrusion](https://user-images.githubusercontent.com/16336129/101645384-b2e06100-3a0c-11eb-91f2-640db52a0db3.jpg)
The wrong lenght is also caused by sketch's position on space (gone after placing it in (0,0,0).

[SheetMetal.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/5659691/SheetMetal.zip)

**Comment by jaisekjames** [comment]
Fixed above issues in 
https://github.com/shaise/FreeCAD_SheetMetal/pull/159

pls check it.

**Comment by dham-eng** [comment]
Hello, jaisekjames,

the lenght issue is solved.

The only thing that still wrong it's the sketch's position bug, where you can not move it in x or y direction manually (it worked for me attaching the sketch to a shapebinder on a test instead of directly moving the sketch through it's properties/equations).

Steps to reproduce:
1 - Create a basebend
2 - Move placement/attachment coordinates of sketch (x or y).

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23463 (Git)
Build type: Release
Branch: master
Hash: adc6db8f32c17e9f67cb82aa7962d1e42ce061c6
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: Portuguese/Brazil (pt_BR)

**Comment by jaisekjames** [comment]
Fixed in above commit. pls check it.

**Comment by luzpaz** [comment]
@dham-eng ping

**Comment by dham-eng** [comment]
Hello, @jaisekjames and @luzpaz, I can confirm that everything seens to work fine now. Thank you!
