### ISSUE TITLE
SheetMetal missing a Qt 'Resource Collection File' (.qrc)

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#163]
Per https://doc.qt.io/qt-5/resources.html  
We'd add it to `Resources/` directory

**Comment by shaise** [comment]
what is it used for if its not an executable?

**Comment by luzpaz** [comment]
In FreeCAD master, it is used to track icons of each workbench + all the translation files. But I wouldn't know how to explain technically why it's of use.

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD/blob/master/src/Tools/dir2qrc.py
