### ISSUE TITLE
Uncorrect bend

### ISSUE THREAD

**Issue by sedatkrn** [shaise/FreeCAD_SheetMetal#185]
freecad 019 and realthunder have got same problem about edge bend.
1- i make a rectangle 300x400 and then create pad from it. 
2- i made one edge to down  bend. edge  demations are 300mm. 
3-  all bend lenght is 20mm  
4- other 3 edge did bend upper.  but it is not coorect bend edge.

![Ekran görüntüsü 2021-03-06 231223](https://user-images.githubusercontent.com/79061314/110219798-60f78c00-7ed2-11eb-92ea-aa4ba9e53923.png)
![Ekran görüntüsü 2021-03-06 231241](https://user-images.githubusercontent.com/79061314/110219806-694fc700-7ed2-11eb-9564-8f57874d1427.png)

it is file :
https://drive.google.com/file/d/1S1tC_uXlMyu8vf47Rqs2GuqeWl5x61SG/view?usp=sharing

**Comment by luzpaz** [comment]
cc @ceremcem

**Comment by ceremcem** [comment]
@luzpaz Why me? :D 

@sedatkrn Somehow the `Invert` property of the feature `Bend` (the feature before `Bend001`) haven't visually applied. I set the `Invert` property of `Bend` to `false` and then `true` again, it is fixed:

https://user-images.githubusercontent.com/6639874/110222416-0581ca00-7ee3-11eb-98e1-7ed689f86656.mp4

I guess it's related with LinkStage3 and not with SheetMetal WB. I also deleted the bend features and created them from scratch, both in your version of LinkStage3 and the latest one as of today, both produced the correct bend.

**Comment by ceremcem** [comment]
As for the intersection, same trick applies: 


https://user-images.githubusercontent.com/6639874/110222716-54c8fa00-7ee5-11eb-965d-f1ac8f46a618.mp4

```
OS: Debian GNU/Linux 10 (buster)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.27270 (Git)
Build type: Release
Branch: LinkStage3
Hash: 32f78691fae500e494879493abc2b74cff9585d3
Python version: 3.7.3
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

**Comment by luzpaz** [comment]
> @luzpaz Why me? :D  

@ceremcem  
https://twitter.com/tc_ulgen/status/1368314503595757570  
:smirk:

**Comment by sedatkrn** [comment]
Very interesting I try again. I made a strove whit freecad. The sheet metal wb extremely important for me. I must make many sheet panel, many bending. Some times the models could be very complicated. Thanks for interesting. Sagolasin bu konuyla ilgilenen bir Türk olması harika.

**Comment by sedatkrn** [comment]
i tried whit freecad 018 last version but bend not work probably. i sening a video about issue
https://drive.google.com/file/d/13Cc-BC_9NRaEr-o44wyUqqT6ODI9SclC/view?usp=sharing

**Comment by ceremcem** [comment]
You are selecting edges, not faces.

**Comment by ceremcem** [comment]
https://user-images.githubusercontent.com/6639874/110237059-c71ff580-7f4a-11eb-8ad1-25966f4146b5.mp4

**Comment by ceremcem** [comment]
> The sheet metal wb extremely important for me. I must make many sheet panel, many bending.

Btw, I strongly recommend enabling `Engineering UX Mode` for those who use this WB in production: 

![image](https://user-images.githubusercontent.com/6639874/110237176-66dd8380-7f4b-11eb-8664-a5a8d9776e8a.png)

**Comment by sedatkrn** [comment]
Mu sheet metal version 2.47 yours 2.45

**Comment by ceremcem** [comment]
Correct. @shaise I can verify that 2.45 has no problems where 2.47 causes above (original) issue.

**Comment by luzpaz** [comment]
> > The sheet metal wb extremely important for me. I must make many sheet panel, many bending.
> 
> Btw, I strongly recommend enabling `Engineering UX Mode` for those who use this WB in production:

Maybe worth adding this screenshot to the README,md file?

**Comment by ceremcem** [comment]
@shaise in v2.47, `Bend type: Material Inside` causes above issue. This bug is introduced by commit https://github.com/shaise/FreeCAD_SheetMetal/commit/f70b7d7.

**Comment by ceremcem** [comment]
@sedatkrn As a workaround, you can use the commit before this bug is introduced: 

1. Go to `%APPDATA%\FreeCAD\Mod\`
2. There should be a `sheetmetal` folder. Rename it (like, `sheetmetal.backup`)
3. Download https://github.com/shaise/FreeCAD_SheetMetal/archive/9b5c3e10f6d4ee84754bfb2807c531eab70ac875.zip
4. Unzip it 
5. Now you should have `%APPDATA%\FreeCAD\Mod\sheetmetal` folder. 
6. Restart FreeCAD

(Sorry, I'm not a Windows user, so steps might not be extremely accurate)

**Comment by shaise** [comment]
> 
> 
> @shaise in v2.47, `Bend type: Material Inside` causes above issue. This bug is introduced by commit [f70b7d7](https://github.com/shaise/FreeCAD_SheetMetal/commit/f70b7d7).

@jaisekjames , can you check this issue? It looks like it happened after your PRs 

shai

**Comment by sedatkrn** [comment]
how i ccheck it? i add chnagged file from github?

**Comment by sedatkrn** [comment]
working perfect  thanks :)
![Ekran görüntüsü 2021-03-07 154313](https://user-images.githubusercontent.com/79061314/110240205-dd827d00-7f5b-11eb-8d8b-ffdf3d76cc8e.png)

**Comment by sedatkrn** [comment]
i tried linkstage and it is working correct :)

![resim](https://user-images.githubusercontent.com/79061314/110240378-af516d00-7f5c-11eb-88a6-50554b7d7872.png)

**Comment by ceremcem** [comment]
Bug is not resolved, please reopen.

**Comment by luzpaz** [comment]
@shaise :point_up_2:

**Comment by sedatkrn** [comment]
is the bug still unrsolved?

**Comment by ceremcem** [comment]
@sedatkrn Waiting for @jaisekjames to respond.

**Comment by sedatkrn** [comment]
Thanks
