### ISSUE TITLE
Customized development of sheet metal design software

### ISSUE THREAD

**Issue by WREQI** [shaise/FreeCAD_SheetMetal#191]
https://www.youtube.com/watch?v=uyzlfdRSlJ8
I want to customize and develop a sheet metal design tool like the one in the video. How much is the price?

**Comment by luzpaz** [comment]
wut?

**Comment by shaise** [comment]
+1

**Comment by luzpaz** [comment]
close this ticket?

**Comment by shaise** [comment]
perhaps so.

**Comment by luzpaz** [comment]
anytime you're ready... :laughing:

**Comment by shaise** [comment]
Not sheetmetal wb related. closing
