### ISSUE TITLE
Offset parameter of Sheetmetal does not work

### ISSUE THREAD

**Issue by berberic2** [shaise/FreeCAD_SheetMetal#210]
See
https://forum.freecadweb.org/viewtopic.php?p=522048#p522021 and
https://forum.freecadweb.org/viewtopic.php?t=60787
for explanation.

**Comment by jaisekjames** [comment]
Please set Bend type to Offset for accept offset value in property editor. 
![offset sheetmetal](https://user-images.githubusercontent.com/44542605/130566139-f118c3c6-6c77-4de2-b9e6-3696912346a1.png)

**Comment by berberic2** [comment]
Oh. thanks
