### ISSUE TITLE
Unfold is failing. ('list indices must be integers or slices, not NoneType',)

### ISSUE THREAD

**Issue by mfraser** [shaise/FreeCAD_SheetMetal#217]
In FreeCAD 0.20, whenever I try to unfold I get this error:
09:43:23  Engineering mode is enabled.
09:44:51  Material found: 0.40ansi
09:44:51  This is a Manual K-factor{'kfactor': 0.4, 'standard': 'ansi'}
09:44:53  Manual K-factor is being used: 0.40 (ansi)
09:44:53  exception at line 2865('list indices must be integers or slices, not NoneType',)
09:44:53  ('list indices must be integers or slices, not NoneType',)
09:44:53  Traceback (most recent call last):
09:44:53    File "/home/mfraser/.local/share/FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 2865, in accept
    s, foldComp, norm, thename, err_cd, fSel, obN  = getUnfold(k_factor_lookup)
09:44:53    File "/home/mfraser/.local/share/FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 2173, in getUnfold
    TheTree.Bend_analysis(f_number, None) # traverses the shape and builds the tree-structure
09:44:53    File "/home/mfraser/.local/share/FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 1328, in Bend_analysis
    self.Bend_analysis(child_info[0], t_node, child_info[1])
09:44:53    File "/home/mfraser/.local/share/FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 1328, in Bend_analysis
    self.Bend_analysis(child_info[0], t_node, child_info[1])
09:44:53    File "/home/mfraser/.local/share/FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 1319, in Bend_analysis
    t_node = self.make_new_face_node(face_idx, parent_node, parent_edge, wires_edge_lists)
09:44:53    File "/home/mfraser/.local/share/FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 1102, in make_new_face_node
    oppVertIndexes = range(len(self.__Shape.Faces[newNode.c_face_idx].Vertexes))
09:44:53  TypeError: list indices must be integers or slices, not NoneType

**Comment by shaise** [comment]
please post this issue on the freecad forum:
https://forum.freecadweb.org/viewtopic.php?f=3&t=60818&p=551252&hilit=sheetmetal+workbench#p551252
and please attach the freecad file that is not working.
