### ISSUE TITLE
Extend leads to no attribute UseSubtraction error

### ISSUE THREAD

**Issue by akshimassar** [shaise/FreeCAD_SheetMetal#240]
sheetmetal version V0.2.51 23 Jul 2022

![aaa](https://user-images.githubusercontent.com/7994369/180751165-4b1bdda8-1a0d-421c-8b01-91c35f69875c.png)

```
12:57:23  Traceback (most recent call last):
  File "/home/akshi/.FreeCAD/Mod/sheetmetal/SheetMetalExtendCmd.py", line 337, in execute
    s = smExtrude(extLength = fp.length.Value,  gap1 = fp.gap1.Value, gap2 = fp.gap2.Value, subtraction = fp.UseSubstraction,
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'UseSubstraction'
```

[test.FCStd.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/9180097/test.FCStd.zip)

Repro is trivial. Part design, new body, new sketch, rectangle, pad, 2mm, select side face, extend -> error.

**Comment by akshimassar** [comment]
I've tried it with 0.19 freecad and with realthunder branch -- result was the same.

**Comment by akshimassar** [comment]
Reverting commit fef6bb2d310c8f8acc62b242ec8bad54385139e4 fixes the issue.

Related to #238 

Just note that correct spelling would be `subtraction`

**Comment by luzpaz** [comment]
Is this still an issue ?

**Comment by akshimassar** [comment]
I haven't checked it with newer versions of the plugin. Let's close it as it should be fixed as per @shaise
