### ISSUE TITLE
 Translation of GUi

### ISSUE THREAD

**Issue by kaktusus** [shaise/FreeCAD_SheetMetal#247]
How likely is this workbench to join the FreeCAD-addons on the Crowdin platform?

I am interested in the author's opinion in this regard.

**Comment by shaise** [comment]
Sorry, not familiar with Crowdin

**Comment by kaktusus** [comment]
[Kuzma30](https://github.com/Kuzma30) Are you able to help a colleague and explain the most important points to him?

**Comment by kaktusus** [comment]
A developer's manual was created:

https://github.com/FreeCAD/DevelopersHandbook/blob/master/technical/translation.md

**Comment by hasecilu** [comment]
From what I have seen on the main FreeCAD Crowdin project almost every day FreeCAD is being translated, on the addons project only 7 external WB are there from more than 100!.
The point is that having the same people that translates main FreeCAD translating the addons will help end users by having a level of consistency on the whole FreeCAD environment.

I'm sure doing it will get more attention from translators.

**Comment by kaktusus** [comment]
@hasecilu
you said it very nicely.

**Comment by luzpaz** [comment]
I think this can be resolved due to https://github.com/shaise/FreeCAD_SheetMetal/blob/master/TRANSLATIONS.md

Edit: Thanks to everyone involved!
