### ISSUE TITLE
missing WB icon in SVG format

### ISSUE THREAD

**Issue by easyw** [shaise/FreeCAD_SheetMetal#27]
Hi @shaise 
it would be possible to have the main WB icon as svg?
(D:\shai\FreeCAD\mkwall_xpm)
In HDPI monitors the actual XPM is little if used inside Selector Tool...
![selector](https://user-images.githubusercontent.com/3032347/37766087-30c2be70-2dc6-11e8-832d-0a12cb134527.png)
Thx
Maurice
PS if you could share the svg file, I could make a PR to switch from xpm to svg 😄

**Comment by shaise** [comment]
Hi Maurice

I've been thinking of changing them for quite some time... Thanks for giving me the incentive. Can you add these Icons and generate PR?
[WBLogos.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/1837537/WBLogos.zip)

**Comment by easyw** [comment]
done a PR https://github.com/shaise/FreeCAD_SheetMetal/pull/28 😄 
PS do you also have the old SMLogo in SVG?
Thx
Maurice

**Comment by shaise** [comment]
Of Course!

Attached. Funny thing is that it was just a trial sketch when I first started SM workbench, and it stayed...
[SMLogoOld.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/1838071/SMLogoOld.zip)

**Comment by easyw** [comment]
thx a lot, I was attached to the 'old' one 😉 

![sm-logo](https://user-images.githubusercontent.com/3032347/37787421-27ea21c4-2dff-11e8-9cde-779510f0d891.PNG)
[SMLogo-Old-New.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/1838615/SMLogo-Old-New.zip)
But the new one is also very fancy 👍 

![sm-logo-new](https://user-images.githubusercontent.com/3032347/37787747-02700a2a-2e00-11e8-8873-a47ebe6a4c8e.png)

Thx for your useful WB :smile:

**Comment by shaise** [comment]
BTW, how do you activate this tool bar? looks more convenient then the drop box.

**Comment by easyw** [comment]
thx to @triplus
https://github.com/triplus/SelectorToolbar

**Comment by shaise** [comment]
Thanks!

**Comment by shaise** [comment]
After considerations, mainly because the new icon does not look good in small size, I reverted to the original Icon with your nice sheen tweak... thanks!
