### ISSUE TITLE
Windows defender reports a Trojan 

### ISSUE THREAD

**Issue by alka66** [shaise/FreeCAD_SheetMetal#271]
If i try to install this addon, Windows Defender show a warning 
"Trojan:Script/Wacatac.B!ml"
![Screenshot 2023-03-26 234423](https://user-images.githubusercontent.com/129009594/227806524-071c6f67-7509-44f4-91c7-15ab059c04fa.png)

**Comment by luzpaz** [comment]
Looks like a false positive

**Comment by alka66** [comment]
Tried again - it works!!!
Thank you for great work.
