### ISSUE TITLE
Changing the workbench's license

### ISSUE THREAD

**Issue by prokoudine** [shaise/FreeCAD_SheetMetal#286]
The Workbench Creation guide [recommends](https://wiki.freecad.org/Workbench_creation) licensing addons under the terms of LGPL2.1 — the same license that FreeCAD source code is available under. The recommendation’s rationale is that it should be possible to ship a FreeCAD distribution, either upstream, or a custom one, with 3rd-party addons that are considered useful.  While a workbench developer is free to choose an alternative license, doing so may impact the long-term viability and use of the workbench and should be considered carefully.

Ondsel would like to integrate the Sheet Metal workbench into its distribution of FreeCAD, because the company’s market study suggests that, just like iwth the Fasteners WB, this feature is expected to be available in 3D CAD programs by default. We want to provide our end-users the best possible experience. There’s a possibility that this workbench then will go back to become part of upstream FreeCAD. However neither the upstream version of FreeCAD, nor Ondsel’s version of FreeCAD can distribute this workbench as long as it’s licensed under the terms of GPL3.

We are asking for a conversation about relicensing this workbench under LGPL2+ or another compatible license to allow wider distribution.

- [x] @shaise
- [x] @JMG1 
- [x] @jaisekjames
- [x] @luzpaz
- [x] @Syres916
- [x] @easyw
- [x] @chappatted
- [x] @realthunder
- [x] @sliptonic
- [x] @riqueenz
- [x] @Roy-043
- [x] @looooo
- [x] @hasecilu
- [x] @alexneufeld
- [x] @mangelozzi
- [x] @rmu75
- [x] @chennes
- [x] @s-light
- [x] @kaktusus
- [x] @ufocia
- [x] @ASzc
- [x] @Jantek
- [x] @bgamari
- [x] @hl037
- [x] @ceremcem
- [x] @thesyndicated
- [x] @mumme74

**Comment by shaise** [comment]
As with Fasteners, I'll be happy to re-license to LGPL2.1. The code is based on @JMG1 's work and one of the main components is @ulrich1a 's sheetmetal unfolder which both are LGPL2 so we are good with that.
It was only by my mistake that the current license is GPL.

**Comment by sliptonic** [comment]
As a contributor, I'm fine with my contributions being relicensed.

**Comment by shaise** [comment]
waiting for response of:
@Syres916, @easyw, @ASzc, @bgamari, @ceremcem, @mumme74

**Comment by rmu75** [comment]
My contribution isn't really noteworthy, I'm ok with relicensing.

**Comment by riqueenz** [comment]
No objection to the license change!

**Comment by hl037** [comment]
No objection on my side neither

**Comment by alexneufeld** [comment]
I have no objection to the license change.

**Comment by hasecilu** [comment]
I agree with the change!

**Comment by s-light** [comment]
i am happy with the change!

**Comment by Jantek** [comment]
I am ok with the change

07.12.2023 20:47:33 Stefan Krüger ***@***.***>:

**Comment by kaktusus** [comment]
As they say in my country I am for and even against
This is an ironic admission that the previous speaker is right.
:laughing:

**Comment by chennes** [comment]
I agree with the change.

**Comment by ufocia** [comment]
I'm OK with LGPL2.1.

**Comment by jaisekjames** [comment]
I agree with the change.

**Comment by mangelozzi** [comment]
I agree with the change. Totally makes sense to integrate it

**Comment by thesyndicated** [comment]
I think I only fixed a typo here, but I'm totally good with the license
change.

**Comment by chappatted** [comment]
I also agree with the change.

**Comment by looooo** [comment]
Not sure if i have contributed to this repo but its ok for me too.

**Comment by Roy-043** [comment]
I have no objections to the LGPL2.1 license.

**Comment by realthunder** [comment]
No objection! Congratulations!

**Comment by JMG1** [comment]
No objections from my side!

**Comment by luzpaz** [comment]
No objection

**Comment by easyw** [comment]
go for it!
sorry being late, but I don't watch very often my GH notifications

**Comment by mumme74** [comment]
No objection, sorry for responding late.
Change as you se fit as long as its an open source license.

**Comment by shaise** [comment]
@ceremcem , @Syres916 

Your responses?

**Comment by Syres916** [comment]
No objection

**Comment by prokoudine** [comment]
@ASzc What's your take on this?

**Comment by ASzc** [comment]
I'm ok with re-licensing to LGPL2.1

**Comment by prokoudine** [comment]
Only up to you now, @bgamari and @ceremcem!

**Comment by ceremcem** [comment]
Hi. Sorry for the delay. I'm okay with the change you propose.

**Comment by bgamari** [comment]
I am fine with relicensing.

**Comment by shaise** [comment]
Great!! All in!
@prokoudine , what is the next step?

**Comment by prokoudine** [comment]
> Great!! All in! @prokoudine , what is the next step?

I can do a PR changing the contents of LICENSE and boilerplates in .py files to LGPLv2.1, unless you want to do that yourself.

**Comment by shaise** [comment]
if you can do it, that would be great!

**Comment by shaise** [comment]
Close as accomplished.
