### ISSUE TITLE
Unfold : export sketch dxf  ===>  does not create a dxf file

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#289]
"Export sketch" does not create a dxf file.
The resulting SVG file is marked as DXF.
![Зняток екрана як 2024-01-02 13-46-13](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/1c1c3f44-8dbf-4a4a-ac0f-e9f43e54ff4b)

A folder with an old version that works.
[sheetmetal_work_dxf.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/13818456/sheetmetal_work_dxf.zip)

**Comment by shaise** [comment]
You are correct! 
Thanks for the catch. 
It should be ok now, please update and test.

**Comment by free777cat** [comment]
![Зняток екрана як 2024-01-04 15-24-04](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/fc1f90af-81eb-47d1-a7f5-44c33dfdb6d2)
![Зняток екрана як 2024-01-04 15-23-31](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/b30154e6-4625-46f2-a218-e653f921ff21)

**Comment by shaise** [comment]
> Question number 2
> Is it possible to make the selection options so that there is only the filename? 

No because there are times that you have several unfold items in the same file.

**Comment by free777cat** [comment]
https://github.com/shaise/FreeCAD_SheetMetal/issues/289#issuecomment-1877066085

**Comment by free777cat** [comment]
Such "extended" file names are very disturbing for further work.

**Comment by free777cat** [comment]
Maybe you will make it possible to choose a "mask" of file names? Of course I can manually fix the code, but having a "switch" would be a better solution.

![Зняток екрана як 2024-01-04 15-05-13](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/ce58ddf5-ae12-40e7-93ab-ab9c6ae8e532)
