### ISSUE TITLE
Mitered bend unfold error

### ISSUE THREAD

**Issue by shrines** [shaise/FreeCAD_SheetMetal#29]
Hey Shai,
I just updated to your latest sheetmetal workbench and decided to try out mitered bends.
Pretty cool!
I did run into a problem, though.  If I make one mitered bend the part unfolds exactly as expected.  If I make a second bend from the face of the mitered bend then the part won't unfold.  Instead I get one of two error messages, depending on which face I select to initiate the unfold.

[Mitered bend.FCStd.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/1853505/Mitered.bend.FCStd.zip)
![unfold error1 180326](https://user-images.githubusercontent.com/7968684/37990615-a7531c62-31bb-11e8-8cbf-46e49775dc8f.PNG)
![unfold error2 180326](https://user-images.githubusercontent.com/7968684/37990627-b2ae3e2a-31bb-11e8-8519-e3e35f642012.PNG)

Regards,
--Steve

**Comment by shaise** [comment]
Hi Steve,

Unfortunately the unfolder code is not mine, and it's rather complicated for me to understand it. It belongs to the very talented Ulrich Bramar. 
can you try his latest macro from here: https://forum.freecadweb.org/viewtopic.php?t=15421#p122997
I'm pretty sure I have updated to his latest version, but I have already heard that sometimes the original works as opposed to the integrated one.
If it does not work, try posting a question in the forum.

shai

**Comment by ulrich1a** [comment]
The problem with the part Mitered_bend is, that the flat sheet with the miter angle has bspline edges and not straight lines (Edges 20 and 16). The following bend (bend001) now produces a <SurfaceOfRevolution object> instead of an <Cylinder object>. The <SurfaceOfRevolution object> is not supported by the unfolding script. It is not planned to support this type surface, as it has no defined radius.

Ulrich

**Comment by luzpaz** [comment]
@shaise Maybe label this as "Won't Fix" ?

**Comment by shaise** [comment]
Agree. how?

**Comment by luzpaz** [comment]
@shaise the same way you made and 'enhancement' label you make one for 'wont fix' and apply it to this ticket. Then close the ticket.

**Comment by shaise** [comment]
thanks. closing
