### ISSUE TITLE
o.SubObjects[0] is out of range

### ISSUE THREAD

**Issue by deveee** [shaise/FreeCAD_SheetMetal#3]
When unfolding is finished, I get an error that o.SubObjects[0] is out of range.

I didn't check the reason, but in PerformUnfold() function you have:

```
      if len(o.SubObjects)>1:
        mw=FreeCADGui.getMainWindow()
        QtGui.QMessageBox.information(mw,"SubelementError","""Only one flat face has to be selected!""")
      else:
        subelement = o.SubObjects[0]
```

changing `else:` line to `elif len(o.SubObjects)>0:` solves this issue.

**Comment by shaise** [comment]
Hi Deveee,
Sorry, I was on vacation, I just saw all you remarks, thanks for your work, I will tend to it ASAP.

**Comment by shaise** [comment]
You are correct. changed "if len(o.SubObjects)>1" to "if len(o.SubObjects) != 1"
