### ISSUE TITLE
Set K-factor for unfolding

### ISSUE THREAD

**Issue by iadenisov** [shaise/FreeCAD_SheetMetal#30]
During the unfold procedure the length block should be dependent from the K-factor. However I do not find the way how to change it. Such setup parameter will be extremely useful.

**Comment by shaise** [comment]
iadenisov,
I definitely agree. Unfortunately the unfold is not my code, I just integrated Ulrich Bramar's Unfold macro. Try leaving a post in the freecad forum.

shai

**Comment by iadenisov** [comment]
I found that author also knows that it is required. 

SheetMetalUnfolder.py
```
# To do: 
# - handle a selected seam
# - handle not-circle-curves in bends
# - detect features like welded screws
# - make a view-provider for bends
# - make the k-factor selectable
# - upfold or unfold single bends

## https://forum.freecadweb.org/viewtopic.php?t=15421#p122997 
 
```

**Comment by shaise** [comment]
K-Factor manipulation added to ver 0.1.30
