### ISSUE TITLE
Clever bending direction

### ISSUE THREAD

**Issue by pierreporte** [shaise/FreeCAD_SheetMetal#304]
When selecting an edge for `SMMakeWall`, the fold is always in the same direction relatively to the reference surface of the part. It could be in the direction closer to the selected edge, while still allowing to invert it

![clever bending](https://github.com/shaise/FreeCAD_SheetMetal/assets/2029853/8fd74c85-e14e-4c74-88bc-6816c248c70e)

**Comment by shaise** [comment]
This is already the case - just to the opposite direction....

**Comment by pierreporte** [comment]
I feel dumb to not have understood it because that works all the time. You can close the issue. Why the behavior is inverted?

**Comment by shaise** [comment]
actually as i remembered it was the other way around. I need to ckeck old versions. perhaps its a bug

**Comment by shaise** [comment]
Yes, indeed it was the correct way before and was changed sometime in 2020. I will fix it even if it brakes saved models.

**Comment by shaise** [comment]
issue fixed now.

**Comment by pierreporte** [comment]
Thank you for the fix.
