### ISSUE TITLE
radius in "Add base shape"

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#312]
It is not possible to set a radius smaller than 1.0mm
![Зняток екрана як 2024-03-17 18-48-51](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/578c18cd-9599-426c-ac52-d7d2a1d6c795)
It is possible to change in the editor.

**Comment by shaise** [comment]
This issue is now fixed. Thanks for the catch
