### ISSUE TITLE
LCS  in "Add base shape"

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#317]

**Comment by free777cat** [comment]
![Зняток екрана як 2024-03-23 23-30-29](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/a09e494d-8237-430c-aeb2-c91be9aa9529)
![Зняток екрана як 2024-03-23 23-32-27](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/fe6c602d-33ef-435f-be94-a4bdac901862)

it will be more convenient 

+ 
![Зняток екрана як 2024-03-23 23-37-40](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/ae9548bc-2b46-46c7-bbd3-1896cde8c0ce)

**Comment by free777cat** [comment]
Please change the LCS position.
It interferes a lot with the design.

**Comment by free777cat** [comment]
This LCS position nullifies all the advantages of using the "Add base shape" function

**Comment by shaise** [comment]
I do not understand your request. Some people like the LCS on the side, some in the center. If I put it in the center someone else will say it is better on the side.

**Comment by free777cat** [comment]
When designing, the base of symmetrical parts is always in the center.
Thus, the model can immediately be used in "Assembly".
It's not just "people like", it's an engineering way.

**Comment by free777cat** [comment]
If the "Bend side" parameter is added, it does not correlate at all with the lateral position.


![Зняток екрана як 2024-03-27 14-24-35](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/7c505c5c-efb2-4e25-bd16-8009396314dd)

**Comment by shaise** [comment]
I can understand the reasoning of putting LCS in the symmetrical center.
But from your image you want it to be at the Celter-Left, What about Center-Center or Center-Right?
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/94bba9e1-700e-4542-b2a7-42ffe8ca87e6)

**Comment by shaise** [comment]
OK. Best thing is to let the user choose origin location. I have added this option. 
It should also work on previously generated base shapes, it you recompute them.
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/6f1f14b2-c0a4-447b-9672-891e091e3268)

**Comment by free777cat** [comment]
You still need to add "invert".
Then all options will be available.


![Зняток екрана як 2024-03-28 13-38-34](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/526ae3fb-0b08-45f5-8b6b-99248a638b86)

**Comment by shaise** [comment]
What do you mean by invert? so the u shape is along Y instead of along X?

**Comment by free777cat** [comment]
![Зняток екрана як 2024-03-28 15-17-16](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/38926668-04d8-4455-b174-cb32b47931ac)
![Зняток екрана як 2024-03-28 15-18-09](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/00405d5d-1dec-4fc3-b781-cd6b09ca7726)
![Зняток екрана як 2024-03-28 15-18-21](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/d431e7dd-0036-4d2e-a851-610d5edc8256)

**Comment by shaise** [comment]
Sorry but I do not see a reason for that. You can just rotate the part. This will just over complicate the tool.

**Comment by free777cat** [comment]
Is it possible to make the "negative" value work?
"invert"

![Зняток екрана як 2024-03-30 09-36-12](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/53620d8f-7d1d-492a-8407-797eca7de5ca)

**Comment by free777cat** [comment]
location ICONs super !!!
