### ISSUE TITLE
object has no attribute 'Object'

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#334]
Traceback (most recent call last):
  File "/home/USER/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalBaseCmd.py", line 295, in claimChildren
    if hasattr(self.Object, "BendSketch"):
               ^^^^^^^^^^^
<class 'AttributeError'>: 'SMBaseViewProvider' object has no attribute 'Object'

[Object.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/15137416/Object.zip)

![Зняток екрана як 2024-04-27 10-12-12](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/24930989-ff35-4f1c-91f4-ef0ec0b25b90)

**Comment by free777cat** [comment]
![Зняток екрана як 2024-04-27 10-12-12](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/555487e2-ffc1-4790-89e3-431c1a759813)

**Comment by shaise** [comment]
Thanks. I'm checking this

**Comment by shaise** [comment]
Should be fixed now.

**Comment by free777cat** [comment]
Дякую !!!
