### ISSUE TITLE
Problem adding italian translation 

### ISSUE THREAD

**Issue by robbeban** [shaise/FreeCAD_SheetMetal#336]
Hallo,
i want add italian translation to SheetMetal addon.
I followed the instructions but I can't find update.sh file in translations directory.
How can I do?
TIA and thanks for your work

**Comment by shaise** [comment]
I think the file you are looking for is [update_translation.sh](https://github.com/shaise/FreeCAD_SheetMetal/blob/master/translations/update_translation.sh). It resides in the translation directory.

**Comment by luzpaz** [comment]
@robbeban bump

**Comment by hasecilu** [comment]
It's almost finished on CrowdIn :+1: ; there is a big open PR here :tada:, after it's merged I expect some changes on strings so we would need to more time to finish translations.

Regarding the script I can updated it after that merge, basically apply the changes I recently made for Fasteners WB.

**Comment by luzpaz** [comment]
@hasecilu this still relevant ?

**Comment by hasecilu** [comment]
Italian is at 74% works fine.

**Comment by luzpaz** [comment]
Closing.
