### ISSUE TITLE
Fold a Wall ===>   Redundant "icons" enabled and working

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#341]
![Зняток екрана як 2024-05-29 10-17-50](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/e006e009-e5c0-4f20-801a-0fe919283a1a)
![Зняток екрана як 2024-05-29 10-18-04](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/0ab1c0bc-4e8c-46f8-89bc-5af94e8f8a93)
![Зняток екрана як 2024-05-29 10-18-21](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/d240eb16-1a11-470e-9924-ae4da2d9c524)
![Зняток екрана як 2024-05-29 10-18-47](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/e987fc9b-6870-4db6-82f6-0ae62f9e3e7d)

**Comment by free777cat** [comment]
When I was working quickly in the morning and made a mistake with the button, I almost fell (in a stupor)

**Comment by shaise** [comment]
Thanks, I will take a look at it.

**Comment by shaise** [comment]
@free777cat , should be ok now.

**Comment by free777cat** [comment]
Ok !!!!!!!!!!!!!
Thanks.
