### ISSUE TITLE
Base Feature images do not match the color theme of the icons

### ISSUE THREAD

**Issue by leoheck** [shaise/FreeCAD_SheetMetal#346]
Sheet metal toolbar icons are awesome. 
I just realized that these icons to select the origin of the Base Feature do not match the theme. 

What do you think about updating the colors of those images using blue instead?

I would also suggest changing the origin dot/ball with something like and + with arrows but this can be too much, maybe.

![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/3d91aa06-a08a-4bb8-8985-19e70947979f)

**Comment by shaise** [comment]
Indeed blue will be better and will be done. However I tested with arrows - too small.

**Comment by leoheck** [comment]
@shaise I am seeing this new way of selecting the origin, it looks nice, but the while thing looks a bit wrong. 
Is this as you expected?

![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/c181e2a0-1a2f-45d6-bbfd-2d5deb20ed41)

**Comment by shaise** [comment]
it is wrong. should look like this:
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/60c1db7b-70d4-47c7-ab28-052ba1b3fa0d)

**Comment by shaise** [comment]
This is rather strange as in your version the icons exceeds the maximum with which is 28 pixels

**Comment by leoheck** [comment]
I am going to check on discord if this is due to the OpenDark Theme.

**Comment by leoheck** [comment]
Maybe the min size property is missing somewhere

**Comment by shaise** [comment]
its not an opendark issue
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/38c3ec00-b760-42e6-b0ad-042dce0ea5da)

**Comment by shaise** [comment]
I will set the min side as well, but should be related to max size

**Comment by leoheck** [comment]
This is my version by the way. Which OS are you using? Perhaps this can be different from one OS to another.

```
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git) AppImage
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * POV-Ray-Rendering
  * Assembly4 0.50.12
  * sheetmetal 0.4.20
  * InventorLoader 1.4.0
  * fasteners.backup1718838499.3717518 0.5.23 (Disabled)
  * ose-piping
  * fasteners 0.5.24
  * asm4_disable_version_check_popup
  * fasteners.backup1718509812.8005707 0.5.21 (Disabled)
  * OpenDark 2024.3.13
  * ProDarkThemePreferencePack 1.0.0
  * Render 2024.6.5
  * OpticsWorkbench 1.0.18
  * lattice2 1.0.0
  * kicadStepUpMod
```

**Comment by shaise** [comment]
i have updated minimum size as well. please try it (you might need to uninstall/reinstall since i did not update the version)

**Comment by leoheck** [comment]
Still the same, and there are these pushXX messages, maybe from this wb.
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/a99cc0c7-f96d-4898-82c9-ccd9aef29b1e)

**Comment by shaise** [comment]
Another possible tweak. Can you try again? (also removed pushXX)

**Comment by shaise** [comment]
If it does not work, I will try to get a ubuntu machine.

**Comment by leoheck** [comment]
Prints were removed but the image/button is still the same.
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/162da244-0ad9-40b2-bd32-a14b6f074da8)

**Comment by shaise** [comment]
I have set the policy to fixed. can you try again?

**Comment by leoheck** [comment]
sure! let me check.

**Comment by leoheck** [comment]
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/4b064c57-0b11-4953-a0e9-45225ac7b7f0)

It is still the same. 
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/e5ee8d43-9972-4b0d-b39c-ad9274339a29)

Perhaps it is a problem with the `AppImage` package.

**Comment by shaise** [comment]
Ok I fired up my ubuntu.
on build 37574, standard theme it looks like this:
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/06e2cb62-fb10-4823-b5c8-cc85a33d9131)
On opendark:
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/84148b31-dc7c-4465-98f0-3cb8c8941a1e)

So it is definitely an opendark issue but only on linux. Can you switch back to standard theme and check to be sure it is the issue?

**Comment by shaise** [comment]
@leoheck , another update:
Using openTheme (dark) instead of openDark seems to solve the issue (need to uninstall openDark)
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/92a5a14d-c63c-4e42-92e1-db702f09f145)

Opendark is actually deprecated, so you should move to opentheme anyways.
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/2beee11e-ec0d-4eaa-9c57-40b0bc810372)

**Comment by leoheck** [comment]
This took me time. Yeah, I confirm the light version works. 
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/e88079a7-d815-461a-927d-7c697d1dd41e)

So the openTheme is the most updated,... this is kind of hard to track. haha thanks.
Thanks for your patience.

**Comment by shaise** [comment]
Yes, With OpenTheme you now have both OpenLight and OpenDark. Directly from the theme drop-down. No need for "Preference Pack" like original OpenDark
