### ISSUE TITLE
Better UI for base shape origin location

### ISSUE THREAD

**Issue by pierreporte** [shaise/FreeCAD_SheetMetal#349]
Currently, the location of part origin is selected in a drop-down list. I propose implementing a more common UI for this kind of selections: a rectangle with 9 buttons.

![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/2029853/e0e42440-4e5c-446c-95da-386d5b8b83e8)

**Comment by shaise** [comment]
Wouldn't it make the panel even taller?

**Comment by pierreporte** [comment]
Yes but there is plenty of room currently as reported in #348.

**Comment by shaise** [comment]
Done.
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/f65a084a-f7ee-4187-b655-2c9240b2ae1a)
