### ISSUE TITLE
Cleaning a field result in a temporary error

### ISSUE THREAD

**Issue by leoheck** [shaise/FreeCAD_SheetMetal#353]
Since the Base Feature is updated every time the user updates the input field, cleaning them results in an error.
I guess, Freecad does a bit differently when updating fields. It waits until the focus leaves from the field. I wouldn't say I like this much but it is better than throwing an error on the Report view. However, sheetmetal could wait until there is a valid value there to recalculate.  What do you think? 

This happened when I removed the thickness there to put a new value. 

![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/4fbb53e3-7318-47a3-b7f9-afc1a40d2f0b)

**Comment by shaise** [comment]
You are definitely correct. Thanks for the catch.
Should be fixed now.

**Comment by leoheck** [comment]
How do you manage these things on github? Do you just push to the master without changing the version? Or do you make branches? Package manager does not see updates. But updating manually I am seeing this.

![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/b3b4de86-1d8b-456a-b0f5-4fc6a83a1467)

**Comment by leoheck** [comment]
This looks working on the current master, thanks. It is way better without red lines on the console.

**Comment by shaise** [comment]
I update the package.xml as I was told. Dont know what the addon manager looks at

**Comment by leoheck** [comment]
Yeah, it took time to update I guess, or maybe because I had changes on my copy of the repo.

**Comment by shaise** [comment]
You are not the first one to complain, so I guess there is still an issue with that
