### ISSUE TITLE
Location of the base feature seems not to changing.

### ISSUE THREAD

**Issue by leoheck** [shaise/FreeCAD_SheetMetal#354]
At least it is not updating when I try to change the Base Feature. I am in a rush so I did not test this exhaustively. 

![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/1277920/953fc561-8542-465a-ae25-1de648ecb604)

**Comment by shaise** [comment]
Strange, it works for me both in windows and ubuntu.

**Comment by leoheck** [comment]
Yeah, it is working fine, I just understood it wrong.
