### ISSUE TITLE
The hole disappears at the bend.

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#363]
The hole disappears at the bend.

The hole disappears at the bend if the diameter is less than the length of the sweep and the hole does not extend beyond the edge of the bend.

https://youtu.be/5vku80OS9XQ

**Comment by shaise** [comment]
Yes this is a tough one. not sure if its an easy fix.
@jaisekjames any ideas?

**Comment by free777cat** [comment]
I experimented a little. 
SheetMetalBendSolid.py
def wrap_face(face, radius, axis, normal, zero_vert, center, zero_vert_normal):
The idea: to make a solid without bending (flat) using a similar method, subtract the solid of the middle part that already exists with a Boolean operation.
The result of the operation will be inverted holes (solid).

Bend two solids separately using the def wrap_face method.

Boolean operation: subtract the solid of the holes (bent from bent)

**Comment by shaise** [comment]
@free777cat , thanks to @jaisekjames this should be fixed now. Please test and close the issue if works.
![image](https://github.com/user-attachments/assets/ec46fbe4-34e3-45fb-9f86-39f8a8061e9d)

**Comment by free777cat** [comment]
![Зняток екрана як 2024-09-09 18-11-45](https://github.com/user-attachments/assets/cf8aeb54-7790-4de9-851e-8ed22cf34ed9)

**Comment by free777cat** [comment]
Now it is impossible to unfold
![Зняток екрана як 2024-09-10 10-53-17](https://github.com/user-attachments/assets/1ad0c0eb-d180-472f-9cfa-29ff9d7f3392)
[ex2_.zip](https://github.com/user-attachments/files/16941522/ex2_.zip)

**Comment by free777cat** [comment]
It may even be so...
[ex1_.zip](https://github.com/user-attachments/files/16941558/ex1_.zip)

**Comment by shaise** [comment]
@free777cat , this is a different issue. Unfolding with holes in the bend did not work even before the current issue was fixed. I think this should be closed and a separate issue open for the unfolder. Mind, though, that this might take time since the unfold feature coder is not active.

**Comment by free777cat** [comment]
The latest version of SM has several bugs. This error returned again. Checked in v1.0, in v1.1dev, RT
