### ISSUE TITLE
Integrate sheetmetal into new HVAC library ?

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#365]
> Foundation and HVAC files are now available in the FreeCAD library for application, enhancements and development. The files are all parametric.

> HVAC and Fundation in Generic objects:
https://github.com/FreeCAD/FreeCAD-library/tree/master/HVAC

> It would be interesting, among another things, if we could **integrate the unfolding tool of the sheet metal workbench with the AC ducts**.

https://forum.freecad.org/viewtopic.php?t=19025

![image](https://github.com/user-attachments/assets/e52c3579-f34b-4733-a2fd-8d808fb29c04)

![image](https://github.com/user-attachments/assets/6cd85df8-a3dd-47b6-8360-dc7bb01a2f44)

**Comment by shaise** [comment]
The unfolder have very strict rules regarding the objects it allows to unfold, I dont think it will be that easy to adapt it to HVAC objects, At least from images I see.
