### ISSUE TITLE
Unfold           k-Fafctor        The number of characters after the period

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#373]
is it possible to increase the number of characters after the dot when entering the k-factor?

**Comment by free777cat** [comment]
![Зняток екрана як 2024-09-21 17-23-50](https://github.com/user-attachments/assets/db1dfecb-267e-47b4-bb8a-1aa145f4165d)

**Comment by shaise** [comment]
added 2 more digits. beyond that its irrelevant.

**Comment by free777cat** [comment]
Could you point out where these changes are made, for me it is of practical importance?
