### ISSUE TITLE
Unfold k-Fafctor 

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#375]
It is not possible to insert data saved in the clipboard  

manual

**Comment by shaise** [comment]
This is a qt issue. cant control it. if you double click the value to select it, then paste will work.

**Comment by free777cat** [comment]
The problem, in my opinion, is that the separator there is a comma and not a period

**Comment by shaise** [comment]
the sperator can be either comma or dot, based on your preferences.
