### ISSUE TITLE
parametric unfold

### ISSUE THREAD

**Issue by rmu75** [shaise/FreeCAD_SheetMetal#376]
Is there a plan to integrate the changes from ondsel branch, esp. the parametric unfold? It kinda sucks that there are 2 versions of this workbench that are beginning to diverge.

**Comment by shaise** [comment]
I definitely agree. There is a pending PR that needs to fixed, but the developer is quite busy. I will wait a bit and if still there is no change, I will try to pick the main features and integrate it manually.

**Comment by rmu75** [comment]
Thanks for the update. My bad, I didn't check pull requests, I see that there is #335 pending, so I will close this issue as a dupe.
