### ISSUE TITLE
How to unfold with one bending line instead of two lines?

### ISSUE THREAD

**Issue by ceremcem** [shaise/FreeCAD_SheetMetal#38]
Currently, unfolding the following part: 

![image](https://user-images.githubusercontent.com/6639874/44262400-91e41880-a223-11e8-820a-2a8291e8abe8.png)

produces following output in DXF file (via TechDraw workbench): 

![image](https://user-images.githubusercontent.com/6639874/44262718-b7bded00-a224-11e8-83d1-322d65a72f37.png)

I added the red line with Gimp, which is what I wanted instead of the green ones (because I'm bending the sheet metal with air bending technique). 

How can I produce one bending line (the red one) instead of these two green ones?

**Comment by shaise** [comment]
I do not know if you have the latest version, but in the latest version the unfolder creates a "projection sketch" with only one line in the middle, ready for bending machine.
(when you press the unfold button, you get a task dialog. make sure the "create projection sketch" is selected)

**Comment by ceremcem** [comment]
That was the answer I was afraid of. I'm using [FC-0.17-Asm3-0.8.2](https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.8.2), btw. Here is a part drawn from scratch and its unfold projection (which seems okay except its visualization, it seems a little bit shifted):

![metal-sheet-projection-success](https://user-images.githubusercontent.com/6639874/44284532-b6afae80-a26a-11e8-9bfb-7f449a5a2f4b.gif)

And here is the non-working attempt for the real case:

![failing-unfold](https://user-images.githubusercontent.com/6639874/44284822-b95ed380-a26b-11e8-93eb-9608cd9780ce.gif)

**Comment by easyw** [comment]
If you post the file I could have a look.

**Comment by ceremcem** [comment]
Absolutely, [here it is](https://github.com/ceremcem/fc-asm3-test/blob/4c2718f9e69ea58e55085fafe95d03121dd50f71/assembly.fcstd)

**Comment by easyw** [comment]
@ceremcem 
you are trying to unfold a link to your object.
A3 branch has a ton of new features that are not covered by FC official WBs as like the external WBs.
SheetMetal doesn't support Links ATM.
This is normal, considering you are working with an experimental dev branch...

If you unfold the original object (or even a simple copy of it) SM will create correctly the unfold sketch.
![sm-a3](https://user-images.githubusercontent.com/3032347/44290230-00eb5c80-a278-11e8-9418-93e791c373c9.png)

**Comment by ceremcem** [comment]
Thank you! 

The main reason for trying to unfold the linked object is that I need to both see the 3D drawing and the unfolded version. As I was only using the `unfold=true` property, I thought that would be only possible with unfolding a linked object (since I needed to track changes (such as cutting windows, etc) on the parent). 

Anyway, since unfold tool displays both folded and unfolded versions, there is no need to create the linked one. 

> BTW: Similar question [here](https://github.com/shaise/FreeCAD_SheetMetal/issues/33)
