### ISSUE TITLE
Translations for task panels

### ISSUE THREAD

**Issue by hasecilu** [shaise/FreeCAD_SheetMetal#383]
I'm working on this but I have a question: **would you like to move `translations` directory inside `Resources` directory?** Most of translated WB have it like this.

**Comment by shaise** [comment]
Hi @hasecilu ,

Please first update to the latest version, there was a massive change after Ondsel merge. 
And yes, move the translation to where you see fit, Just make sure all translation scripts are updated

**Comment by hasecilu** [comment]
Is the file lookup.ui file really needed? I don't think so, deleting it...

**Comment by shaise** [comment]
There are several ui files added by Ondsel that are not used yet but planned to be, so I think they should remain in the code.
Having said that, lookup.ui looks like a junk file, so yes, please remove it.
