### ISSUE TITLE
I'm sorry, of course, but some bullshit happened (so says one little person)

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#386]
"Add base shape" creates two bodies
realthunder/FreeCAD/releases  Stable 2024.10.03

![Зняток екрана як 2024-10-20 09-32-45](https://github.com/user-attachments/assets/3738a094-f520-4ed2-93c8-ecdefb7b2aa4)
![Зняток екрана як 2024-10-20 09-33-10](https://github.com/user-attachments/assets/7c715760-4bb8-45ed-9ff4-202a776b0867)

**Comment by shaise** [comment]
He He! nice redundancy.... :)
Ok I'm on it.

**Comment by shaise** [comment]
Fixed. It seems Ondsel's version only permits base shape inside a body.

**Comment by free777cat** [comment]
Fold a Wall
1.Improper location of the fold line
2.Sketch doesn't hide
![Зняток екрана як 2024-10-20 12-32-35](https://github.com/user-attachments/assets/f5cafba4-a392-4f53-ab7c-ddb7f317c3b0)
![Зняток екрана як 2024-10-20 12-33-27](https://github.com/user-attachments/assets/04c0ce99-4427-4e86-975b-3a2e91841dd4)
![Зняток екрана як 2024-10-20 12-45-01](https://github.com/user-attachments/assets/a19af2a5-222e-44cf-9eb4-44961a84019d)

**Comment by free777cat** [comment]
Ondsel's version
I would be very careful using this!!!

[https://discord.com/channels/1180269060169154620/1197656610361843812/1284566314899341436](url)

![Зняток екрана як 2024-10-20 12-54-21](https://github.com/user-attachments/assets/5fa6ee5f-2cd0-4692-99c8-031e8e20c000)

**Comment by shaise** [comment]
This is very disturbing. I wish I knew it before.

**Comment by luzpaz** [comment]
@free777cat do you mind posting the full About info of the versions you're reporting about? It just makes triage easier. TIA

**Comment by free777cat** [comment]
https://github.com/realthunder/FreeCAD/releases



[code]
OS: Linux Mint 22 (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 2024.1006.0.14555 (Git shallow) AppImage
Build type: Release
Branch: (HEAD detached at 20241003stable)
Hash: 8058dcf52c2661edabf36d8147d5b8a187378d2d
Python 3.11.9, Qt 5.15.13, Coin 4.0.1, Vtk 9.2.6, OCC 7.7.2
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 
  * FEMbyGEN 2.2.0
  * QuickMeasure 2022.10.28
  * Sketcher
  * frame 0.1.1
  * Assembly4 0.50.6
  * mbdyn-dynamics
  * fasteners 0.4.72
  * lattice2 1.0.0
  * FEM_FrontISTR 0.1.0
  * DynamicData 2.56.0
  * sheetmetal 0.5.1
  * Defeaturing 1.2.2
  * dxf-library
  * Estimate 0.1.2
  * ExplodedAssembly
[/code]

**Comment by free777cat** [comment]
> This is very disturbing. I wish I knew it before.

This is the file that the user writes about (this is not my post)
[file.zip](https://github.com/user-attachments/files/17450109/file.zip)

**Comment by shaise** [comment]
Thank you. This bug was fixed. Please uninstall and reinstall sheetmetal. I did not change the version yet.

**Comment by free777cat** [comment]
When creating BaseBend 
![Зняток екрана як 2024-10-21 13-19-15](https://github.com/user-attachments/assets/f160b8d9-eb64-476a-a260-9ddc6b1cf67f)
Sketch doesn't hide

**Comment by shaise** [comment]
Version 5.0.2 should fix the baseband not hiding.

**Comment by free777cat** [comment]
If the topic is about all kinds of bullshit...
Should a picture be added to the description?

https://support.ptc.com/help/creo/ced_modeling/r20.5.0.0/en/index.html#page/ced_modeling/OSDM_Main/SheetParts_KFactor.html

![Зняток екрана як 2024-10-22 10-47-16](https://github.com/user-attachments/assets/fc43a110-1d7d-45bf-9385-3a3ac5cb5289)

**Comment by free777cat** [comment]
Have you already seen the news about the closure of Ondsel?

**Comment by shaise** [comment]
I have heard very little. Are they closing the entire project? Is there an announcement anywhere?

**Comment by free777cat** [comment]
https://ondsel.com/blog/goodbye/

**Comment by free777cat** [comment]
They had plans to create "built-in" SheetMetal - an idea that I personally did not like very much...

**Comment by shaise** [comment]
They wanted both sheetmetal and fasteners built in. These are the most used external workbenches. (much more then some internal ones - like robot)

**Comment by free777cat** [comment]
Couldn't this lead to a certain "monopoly" of sheet metal and fasteners from the point of view of code development?
In my opinion, this would reduce the openness of the code and the speed of responding to problems.

**Comment by shaise** [comment]
I'm not concerned about the "monopoly". The non-monopoly of assembly WB was in my opinion a problem with so many versions.
However I AM concerned about the development and the responsiveness to issues.
That why I think it should be like blender add-ons. The popular ones should be bundled with the release, but you can always disable/enable/update it via the addon manager.

**Comment by free777cat** [comment]
> The popular ones should be bundled with the release, but you can always disable/enable/update it via the addon manager.
That would be very correct. There are people who have no idea about sheetmetal.

**Comment by free777cat** [comment]
Look at this

**Comment by shaise** [comment]
Thanks. Working on it

**Comment by shaise** [comment]
Sorry about that. still issues from the merging with Ondsel.

**Comment by free777cat** [comment]
Thanks

**Comment by luzpaz** [comment]
@free777cat can you rename this ticket to be more relevant and descriptive of the issue ?
