### ISSUE TITLE
Unfold_Sketch Problem 

### ISSUE THREAD

**Issue by lryng** [shaise/FreeCAD_SheetMetal#387]
When performing the Unfold function with the Sketch option. Sketch is rotated 180 in the wrong axis.
![Unfold_sketch Problem](https://github.com/user-attachments/assets/27caddc7-596a-481f-9829-26bc16795e3f)
[Sheet Metal Unfold_Sketch Problem.zip](https://github.com/user-attachments/files/17451506/Sheet.Metal.Unfold_Sketch.Problem.zip)

**Comment by shaise** [comment]
please add freecad info (help -> about, then press "copy to clipboard")

**Comment by lryng** [comment]
![image](https://github.com/user-attachments/assets/00a21c1b-e514-45eb-9711-a07bfa683bf0)

**Comment by shaise** [comment]
Strange, I use the same freecad version but I can not load the example file (as if its from old version, or realthunder linkstage version)

**Comment by lryng** [comment]
I tried again to make it unfold and right now everything is okay.
Sorry for the problem 
![Unfold_sketch Problem_solved](https://github.com/user-attachments/assets/29eb03ae-5e66-4f22-9c7a-797f07dd630c)
