### ISSUE TITLE
Add issue template to bugtracker 

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#390]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Should ask users to 
* provide their full [About](https://wiki.freecad.org/About) info
* zip up an example .fcstd file and drag/drop it into Github textbox so that it auto-attaches to ticket
* provide a screenshot or even better a screencast of the issue to help devs/testers recreate
* step-by-step instructions to recreate issue

**Comment by shaise** [comment]
Nice!
Is there a ready template I can use?

**Comment by luzpaz** [comment]
Modify the existing upstream template? https://github.com/FreeCAD/FreeCAD/blob/main/.github/ISSUE_TEMPLATE/PROBLEM_REPORT.yml

**Comment by shaise** [comment]
Thanks! I will take a look

**Comment by hasecilu** [comment]
Hi, recently I also created them for my WBs. Here is a example: https://github.com/bilbaomakers/StemfieWB/commit/f65f169208173624994134a15ddc5227ba81fa11

**Comment by shaise** [comment]
@luzpaz , @hasecilu 
Thanks for your help! 
I have added the bug report / feature request templates.

**Comment by luzpaz** [comment]
Well Done!
