### ISSUE TITLE
Extruded Cutout does not work in realthunder version

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#395]
Extruded Cutout does not work in realthunder version

09:56:33  Running the Python command 'SheetMetal_AddCutout' failed:
Traceback (most recent call last):
  File "/home/Хата/.local/share/FreeCAD/Mod/sheetmetal/./ExtrudedCutout.py", line 382, in Activated
    SMBody = selected_object.getParent()
             ^^^^^^^^^^^^^^^^^^^^^^^^^

'FeaturePython' object has no attribute 'getParent'

[code]
OS: Linux Mint 22 (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 2024.1006.0.14555 (Git shallow) AppImage
Build type: Release
Branch: (HEAD detached at 20241003stable)
Hash: 8058dcf52c2661edabf36d8147d5b8a187378d2d
Python 3.11.9, Qt 5.15.13, Coin 4.0.1, Vtk 9.2.6, OCC 7.7.2
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 

  * sheetmetal 0.5.4

[/code]

**Comment by shaise** [comment]
Is it same as #392?

**Comment by free777cat** [comment]
I couldn't find #392 today. Decided that this post was not published.
Added error view

**Comment by shaise** [comment]
Try now

**Comment by free777cat** [comment]
Everything is fine now. Thank you!

**Comment by free777cat** [comment]
In my opinion, the function icon is very uninformative.
Maybe the look like in the picture better reflected the idea of ​​the function.
![Зняток екрана як 2024-11-13 12-05-03](https://github.com/user-attachments/assets/0f53a1ee-755b-4109-b158-9cbd13ba3e10)

**Comment by shaise** [comment]
It difficult to make that small

**Comment by free777cat** [comment]
I tried in GIMP.
If you lower the existing one a little, there should be enough space.   Visually it looks clearer.

**Comment by free777cat** [comment]
Extruded cutout (normal to thickness) from extrusion sketch.

Such an explanation will more accurately reflect the essence of the function.
