### ISSUE TITLE
Unfolding Problem when two Flanges meet at Right Angles and the Bend Radius equals the Pad Length

### ISSUE THREAD

**Issue by DoctorBit** [shaise/FreeCAD_SheetMetal#4]
Hardware:
Intel Core i5-2500K Sandy Bridge
Intel HD Graphics 3000

Software:
OS: Linux Mint 17.2 Rafaela
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.6700 (Git)
Build type: None
Branch: releases/FreeCAD-0-16
Hash: 7b925d11aa69ac405b423635adb1e2833f18a817
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 6.8.0.oce-0.17

SheetMetal Workbench V0.0.13

To reproduce the problem:
1) Create a sketch of a right-angled triangle. A square works too.
2) Pad to 1 mm (not the default of 10 mm). This matches the default bend radius of 1 mm.
3) Add bends to both legs of the right-angled triangle (not the hypotenuse!).
4) Unfold

Description of problem: 
One of the faces that should meet the right angle has one corner misplaced.  It looks to me like a sign problem - something is being added to a coordinate when it should be subtracted.

This bug only happens when:
1) The sketch contains a right angle - an equilateral triangle unfolds without problem.
2) The bend radius exactly matches the pad thickness.

**Comment by ulrich1a** [comment]
You may know that Shaise had integrated my macro for sheet unfolding into the workbench.
You may try this new version of the macro.
Unfortunately I have actual no time to make the changes for including it into the workbench.
[sheet_ufo17.py.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/235406/sheet_ufo17.py.zip)

Ulrich

**Comment by shaise** [comment]
The latest unfolder works on this example. Thank you Ulrich.
I have updated the WB to use this latest version.
DoctorBit,
Please test and comment.
Shai

**Comment by DoctorBit** [comment]
Thanks guys, that got it!  I'm marking this issue closed. :+1:
