### ISSUE TITLE
Bend - two questions

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#409]
### Describe your issue

![Зняток екрана як 2024-11-29 10-54-06](https://github.com/user-attachments/assets/4c20bd40-7360-4cc1-9219-51e0104a7e7f)
1. must be added gap1, gap2   -  the design cycle will be completed
![Зняток екрана як 2024-11-29 11-00-27](https://github.com/user-attachments/assets/7432a509-97df-40fc-91b7-fcf7e99e5bfa)

2. When you reopen the task panel for bend (double-click on bend ) and close it, a notification is issued:

08:11:57  Traceback (most recent call last):
  File "/home/X/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalCmd.py", line 1860, in unsetEdit
    Gui.Selection.setSelectionStyle(Gui.Selection.SelectionStyle.NormalSelection)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'AttributeError'>: module 'Selection' has no attribute 'setSelectionStyle'

### FreeCAD version info + SheetMetal WB version

```shell
[code]
OS: Linux Mint 22 (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 2024.1006.0.14555 (Git shallow) AppImage
Build type: Release
Branch: (HEAD detached at 20241003stable)
Hash: 8058dcf52c2661edabf36d8147d5b8a187378d2d
Python 3.11.9, Qt 5.15.13, Coin 4.0.1, Vtk 9.2.6, OCC 7.7.2
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 

  * sheetmetal 0.5.10

[/code]
```

**Comment by shaise** [comment]
Side A and Side B are the gaps 1 and 2...
Also other parameters missing. everything in progress now. I'm adding GUI to all other sheetmetal functions

**Comment by free777cat** [comment]
I think it is not one and the same

gaps
![Зняток екрана як 2024-11-29 11-17-27](https://github.com/user-attachments/assets/d202e4a3-3678-4eb7-856b-b0b727ae670d)
![Зняток екрана як 2024-11-29 11-17-49](https://github.com/user-attachments/assets/7f1e8721-ac4a-45dc-a3e9-899b3aff04ad)

Side A and Side B
![Зняток екрана як 2024-11-29 11-18-29](https://github.com/user-attachments/assets/874e9493-f3d9-48de-b7c4-b790cacdd270)
![Зняток екрана як 2024-11-29 11-18-41](https://github.com/user-attachments/assets/278df935-f725-4270-a656-731167201f1b)
![Зняток екрана як 2024-11-29 11-19-39](https://github.com/user-attachments/assets/00a1a64f-97ce-4118-9226-edf6b10bda88)

**Comment by free777cat** [comment]
++ gap1, gap2

**Comment by shaise** [comment]
You are correct!
working on it.
Regarding the error message it is only on linkstage version. Its not supporting multi select (or maybe doing it otherwise) Anyway, I will at least suppress this error.

**Comment by shaise** [comment]
by the way, do you see the advances parameters as well?

![image](https://github.com/user-attachments/assets/5effdeee-ad52-4be3-80f6-6183625b9b45)

**Comment by free777cat** [comment]
Sorry for the delay in replying. Due to shelling by the Russians, we have outages with electricity and the Internet (they just turned it on).
In my opinion, the idea with tabs is very successful. I will practically check it tomorrow.
![Зняток екрана як 2024-11-30 02-12-07](https://github.com/user-attachments/assets/28952dec-7a88-476e-86a8-22cec916e458)

**Comment by free777cat** [comment]
Maximum Extend Distance 
reduce to the form
Max Extend Distance

this would reduce the overall width
A slightly narrower menu is easier to work with

**Comment by shaise** [comment]
@free777cat , Thank you for helping me with sheetmetal, especially with the condition in the Ukraine.
I have changed the Max Extend as you have suggested.

**Comment by free777cat** [comment]
Thank.
Didn't we deserve "Relief Cuts" on the other "rib" "Bend"? ))
![Зняток екрана як 2024-11-30 12-32-06](https://github.com/user-attachments/assets/cf4458c2-2069-4b20-8e9c-154d83e742b6)

**Comment by free777cat** [comment]
Maybe it's difficult, but another "Relief Cuts_2" menu on this tab will look very nice))

**Comment by shaise** [comment]
You mean different parameters for relief cut 1 and 2?

**Comment by free777cat** [comment]
Yes. 
But it is possible to make       relief cut_2 = relief cut_1        according to the label

**Comment by free777cat** [comment]
Fold a wall - menu
![Зняток екрана як 2024-11-30 13-13-11](https://github.com/user-attachments/assets/60014011-24e2-45c8-9083-2c1e5b9c48cf)
invert   -   add parameter

Flip Direction  -   rename parameter  ( invertbend )

**Comment by shaise** [comment]
Thank you. Fixed the title.
Regarding invert bend, I'm using the design as decided by the Design Work Group. https://github.com/shaise/FreeCAD_SheetMetal/issues/324
