### ISSUE TITLE
Changing bending line color by default

### ISSUE THREAD

**Issue by ceremcem** [shaise/FreeCAD_SheetMetal#41]
For helping mechanical operations, it would be nice to have bending lines in different color on unfold.

**Comment by shaise** [comment]
I Agree. Unfortunately freeCad sketch has no option for separate line colors.

**Comment by easyw** [comment]
it would be nice to separate the sketches like in commercial sw:
1) the unfold external outline
2) the fold lines
3) the holes/internal cuts

then different colors can be handled too.

https://forum.freecadweb.org/viewtopic.php?f=21&t=30000#p247481
https://forum.freecadweb.org/viewtopic.php?f=3&t=28331&p=241213#p229724
https://forum.freecadweb.org/viewtopic.php?f=3&t=27928&p=252918#p252891

**Comment by shaise** [comment]
I thought about this solution. (it is similar to what I did on Path Simulator)
I did not want to generate too much objects on the tree view. However, perhaps I will add a check box to the unfolder task letting the user decide if to generate separate sketches.
This will at least separate the bend lines. For the internal features to be separate I need Ulrich's help.

**Comment by shaise** [comment]
Done. 
(At least for bend lines)

**Comment by ceremcem** [comment]
Where do we set "bend lines color"?

**Comment by shaise** [comment]
Right now there is no way. Is this a real need?

**Comment by ceremcem** [comment]
I can't say that it's blocker, but yes, it would remove the great burden of updating unfolded output.

**Comment by shaise** [comment]
OK. 
Added color selection as well.

**Comment by ceremcem** [comment]
To remove any misunderstanding, I meant the following lines:

![image](https://user-images.githubusercontent.com/6639874/45592347-facdc600-b972-11e8-8d5d-769a80b123eb.png)

If there is no misunderstanding, I have to say I didn't find the place to set the default bend line color. I've looked into 
* menu 
* tools/edit parameters/workbench/...
* tools/edit parameters/preferences/mod/...

**Comment by shaise** [comment]
When you open the unfold task now, you see the colors on the side and you can change it.

**Comment by ceremcem** [comment]
Now I see it, thanks! (FreeCAD warns users that FreeCAD should be re-opened after a first WB install, but it doesn't warn for WB updates. That might be the cause)

**Comment by ceremcem** [comment]
Unfortunately changed line colors are not meaningful until the TechDraw preserves the line colors while generating projections: https://github.com/WandererFan/FreeCAD-TechDraw/issues/64

**Comment by shaise** [comment]
Yes, I agree.
