### ISSUE TITLE
BendCornerPanel.ui file missing

### ISSUE THREAD

**Issue by live2cycle** [shaise/FreeCAD_SheetMetal#410]
### Describe your issue

When I attempt to do a bend I get a failure that appears to be caused by a missing file, BendCornerPanel.ui. 
Checking ~/.local/share/FreeCAD/Mod/sheetmetal/Resources/panels there is no such file

-----
Traceback is as follows:

Running the Python command 'SheetMetal_AddBend' failed:
Traceback (most recent call last):
  File "/home/bjensen/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalBend.py", line 377, in Activated
    dialog = SMBendTaskPanel(newobj)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjensen/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalBend.py", line 300, in __init__
    self.form = SheetMetalTools.taskLoadUI("BendCornerPanel.ui")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjensen/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalTools.py", line 222, in taskLoadUI
    return Gui.PySideUic.loadUi(path)           
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in <module>

Cannot open file

### FreeCAD version info + SheetMetal WB version

```shell
OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * sheetmetal 0.5.10
```

**Comment by shaise** [comment]
Sorry about that. added.
