### ISSUE TITLE
Make Base Wall  -  RT   error

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#422]
### Describe your issue

Make Base Wall  -  RT   error
https://youtu.be/gqkraLS11PE

13:28:40  Running the Python command 'SheetMetal_AddBase' failed:
Traceback (most recent call last):
  File "/home/X/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalBaseCmd.py", line 270, in Activated
    newObj, activeBody = SheetMetalTools.smCreateNewObject(selobj, "BaseBend")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/X/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalTools.py", line 309, in smCreateNewObject
    if not smIsOperationLegal(activeBody, baseObj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/X/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalTools.py", line 429, in smIsOperationLegal
    if smIsPartDesign(selobj) and not smBelongToBody(selobj, body):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/X/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalTools.py", line 424, in smIsPartDesign
    return isinstance(obj.getParent(), Part.BodyBase)
                      ^^^^^^^^^^^^^

'Sketcher.SketchObject' object has no attribute 'getParent'

### FreeCAD version info + SheetMetal WB version

```shell
[code]
OS: Linux Mint 22 (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 2024.1006.0.14555 (Git shallow) AppImage
Build type: Release
Branch: (HEAD detached at 20241003stable)
Hash: 8058dcf52c2661edabf36d8147d5b8a187378d2d
Python 3.11.9, Qt 5.15.13, Coin 4.0.1, Vtk 9.2.6, OCC 7.7.2
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 

  * sheetmetal 0.6.1

[/code]
```

**Comment by shaise** [comment]
It is becoming more and more difficult to be compatible with both versions...
Ok this is fixed now.

**Comment by free777cat** [comment]
Thank you
