### ISSUE TITLE
Please consider using GitHub tags and releases

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#44]
https://stackoverflow.com/questions/18216991/create-a-tag-in-github-repository

**Comment by shaise** [comment]
is there any recommended system to follow?

**Comment by luzpaz** [comment]
Honestly you already have one. You'd just tag any minor version changes and tag and  release major version changes.

**Comment by shaise** [comment]
Great. Will do.

**Comment by ceremcem** [comment]
Also, would you consider using Github tags? Like `bug`, `feature request`, `discussion`, etc...

**Comment by shaise** [comment]
I don't really understand what is a meaning of tagging a version as a 'discussion' or 'bug'

**Comment by ceremcem** [comment]
You can add such labels to the issues:

![image](https://user-images.githubusercontent.com/6639874/45805892-65ab3400-bcc8-11e8-9de9-f81004062519.png)

...which would be quite informative for us and newcomers. You can use the tool on the right side inside an issue: 

![image](https://user-images.githubusercontent.com/6639874/45806112-e4a06c80-bcc8-11e8-847c-1ae5d883d535.png)

...and of course, create new ones: 

![image](https://user-images.githubusercontent.com/6639874/45806220-29c49e80-bcc9-11e8-9f62-8865b8a6a615.png)

**Comment by shaise** [comment]
OK I see, this is not a tag, it is a label, and used for issues. Makes sense now.

**Comment by ceremcem** [comment]
Oh, my mistake!

**Comment by luzpaz** [comment]
Request, adding a little more consistency. Last tag would be very much welcome

![image](https://user-images.githubusercontent.com/4140247/114024765-6e41c680-9842-11eb-938c-5cf5581b60ca.png)

**Comment by luzpaz** [comment]
@shaise can we start doing this?

**Comment by shaise** [comment]
what needs to be done here?

**Comment by luzpaz** [comment]
@shaise the only thing is to also start using releases and release tags (https://github.com/shaise/FreeCAD_SheetMetal/issues/44#issuecomment-815740954). Would you be in to that ?

**Comment by shaise** [comment]
So every time I update the version, add a tag as well?

**Comment by luzpaz** [comment]
Yea, makes sense to me.

**Comment by shaise** [comment]
will do.

**Comment by luzpaz** [comment]
:+1:
