### ISSUE TITLE
Will unfolding an object with a modified bending be supported?

### ISSUE THREAD

**Issue by ceremcem** [shaise/FreeCAD_SheetMetal#45]
Currently if we touch the bend, it can't be unfolded: 

![image](https://user-images.githubusercontent.com/6639874/45707878-ae5bd380-bb88-11e8-9058-97afa1d3bf55.png)

Will it be supported?

**Comment by easyw** [comment]
The hole should applied before the folding in normal workflow.

**Comment by ceremcem** [comment]
Would you give a quick example? I'm not sure I could understand this.

**Comment by easyw** [comment]
If you want to make a folded sheet metal, you start from a plain sheet and then you apply holes and cuts, and finally you bend it. This is the mechanical process. 
The same has to be done when designing your part to be bend ... hole must be applied before the bending, or on plain part of the sheet metal.

**Comment by ceremcem** [comment]
> you start from a plain sheet and then you apply holes and cuts, and finally you bend it. This is the mechanical process.

I think the reverse is also possible: If you cut the material according to its projection (with laser cut, for example) and then bend, It's possible to place - e.g. - a socket right on the bending radius.

**Comment by easyw** [comment]
so you want to cut the sheet and hope that when bend on the cut your metal will follow your cut with the bending?
... I think you never tried to bend a metal did you?

**Comment by ceremcem** [comment]
> did you?

Yes, I did, but I've never had a chance to try what I'm talking about earlier. There are cases: 
1. The material doesn't have to be a metal. 
2. The material doesn't have to be bent with air bending technique. It can be bent with a mold. 
3. I can see no reason about why bending won't follow the cut: 

![image](https://user-images.githubusercontent.com/6639874/45714118-6e511c80-bb99-11e8-8e0e-82c3044aaa74.png)

![image](https://user-images.githubusercontent.com/6639874/45714484-65ad1600-bb9a-11e8-9c40-e1e15ede962e.png)

**Comment by easyw** [comment]
1) in your first image it is clear the holes have been added before the bend (moreover you can see a deformation on the bend)
2) in the second image the cut is parallel to the direction of the bending (is a rectangular cut), so the metal will not 'explode' and moreover the cut has been applied before the bend.
Moreover, also on rectangular and 'parallel' cuts, you need to consider a minimum margin of the cut to avoid that the metal will 'explode'.

**Comment by ceremcem** [comment]
I understand that this is not a brilliant operation. I guess it's better to make some experiments with manually calculated drawings and if it has some level of success, then this issue might be re-opened. Thank you for the explanations.
