### ISSUE TITLE
'Relif' is a typo?

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#52]
https://github.com/shaise/FreeCAD_SheetMetal/blob/master/SheetMetalCmd.py#L650-L651

Saw it in this [thread](https://forum.freecadweb.org/viewtopic.php?f=22&t=25281&p=281022#p281022)
specifically in this image:  
![image](https://user-images.githubusercontent.com/4140247/51422591-37a70500-1b7f-11e9-8e01-92564e1d80fc.png)

**Comment by shaise** [comment]
yes indeed. Its from a feature pull request I missed. If I change it back will it break loading of old files? (I will change only the display name, not the variable)

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/51426749-0fd69200-1bbd-11e9-9068-c893fc79220e.png)

What's the hard in just changing all instances of it in the source, committing it to a separate branch, running it and seeing if it crashes?

**Comment by shaise** [comment]
It will not crash, but if I load an old file that was saved with the wrong spelling, It will not load.

**Comment by shaise** [comment]
OK, there are two options:
1. change most typos to Relief, but leave internal property names to relif, this will be compatible with old files, but will display correctly for the user.
2. change everything to Relief. This will not crash when loading old files, but any editing to sheetmetal featuers will reset relif values, and will display double features on the feature list (only for old files).

What do you think is best?

**Comment by luzpaz** [comment]
Fast method is 1
Smart method is 2
Is there a way to write some code that when encountering the misspelling could auto-change it ?

**Comment by shaise** [comment]
Theoretically it is possible to correct, but then you will have "relif" in the code since you have to ask if a parameter is "relif" then change to relief.... I think its an ugly patch just for typo.
method 2 is easy to do, but if you load old files, you will see 2 parameters in the properties list: both relif and relief, so it is ugly ad well....
The first method means only internal parameters (at 4 places) will be relif but it will not be visible to the end user. 
I can do any of the 3 you like.

**Comment by luzpaz** [comment]
I'm for being `future friendly`...so I'm for method 2 if people can quickly delete the `relif` parmeter. Eventually, the problem will disappear as more people learn and use this Workbench.

**Comment by shaise** [comment]
Friendly it is!
Done.

**Comment by luzpaz** [comment]
Thank you!
