### ISSUE TITLE
Miterangle not working anymore

### ISSUE THREAD

**Issue by dmun19** [shaise/FreeCAD_SheetMetal#56]
Hallo,

Freecad 0.18 and latest sheetmetal addon: Miterangle is not working anymore. See attached screenshot.
Tested with Freecad 0.18 and an older sheetmetal addone too and the old addon works fine, see screenshot number two.
![screenshot-1](https://user-images.githubusercontent.com/47369911/52919459-06972d00-3303-11e9-99df-2fa0e530bbda.jpg)
![screenshot-2](https://user-images.githubusercontent.com/47369911/52919460-06972d00-3303-11e9-960f-42ff5fbdf7a0.jpg)

**Comment by jaisekjames** [comment]
can you check with setting Auto miter to false?

**Comment by dmun19** [comment]
Okay, that works. Thank you.
