### ISSUE TITLE
Fold on sketch line breaks, when bending angle is greater than 99 degrees

### ISSUE THREAD

**Issue by otomov** [shaise/FreeCAD_SheetMetal#63]
Hi,

OS: Ubuntu 16.04.6 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13541 (Git)
Build type: None
Branch: releases/FreeCAD-0-17
Hash: 9948ee4f1570df9216862a79705afb367b2c6ffb
Python version: 2.7.12
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

SheetMetal v 0.2.30
I tested the new feature - Fold-on-sketch-line, and I found quite strange behaviour then folding angle is > 99 degrees.
[Example.fcstd.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/3012560/Example.fcstd.zip)

**Comment by luzpaz** [comment]
Should be fixed by @jaisekjames in be856b78cefe64db968de35102bc535b9c034db4
