### ISSUE TITLE
Bending across sketch created axis not working

### ISSUE THREAD

**Issue by jaessy77** [shaise/FreeCAD_SheetMetal#93]
Hi,
first: a really great workbench.

Im struggeling with the bending feature along a axis (which would be really helpful when folding rigid-flex PCB models).

Even a simple example wich a padded sketch fails at all.

SheetMetal is installed via Addon Manager and shows "Sheet Metal V0.2.31"

I select the face from Pad_Plate and then the Sketch_Bendline and hit the button.
It ends up in "Fold with an exclamation mark" and of course a non-folded result.

In Traceback I can see:
Traceback (most recent call last):
  File "C:\Users\mja\AppData\Roaming\FreeCAD\Mod\sheetmetal\SheetMetalFoldCmd.py", line 203, in execute
    invertbend = fp.invertbend, selFaceNames = fp.baseObject[1], MainObject = fp.baseObject[0])
  File "C:\Users\mja\AppData\Roaming\FreeCAD\Mod\sheetmetal\SheetMetalFoldCmd.py", line 104, in smFold
    edge = Axis.Edges[0]
<class 'IndexError'>: list index out of range

Do have the same problem ?

![image](https://user-images.githubusercontent.com/31255586/61873175-9611bf00-aee5-11e9-84ba-efa1a3690630.png)

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16117 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: dbb4cc6415bac848a294f03b80f65e888d531742
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

**Comment by jaisekjames** [comment]
shaise, Could you pls change line 90 & 92[instead of division to multiply] in SheetMetalFoldCmd.py to

offset = thk * kfactor
offset = thk - ( thk * kfactor )

to fix this bug

**Comment by shaise** [comment]
done. thank you.

**Comment by jaessy77** [comment]
Hi @jaisekjames  and @shaise ,

thank you very muich for the bug fix. Now it works propper.

You both did a great job !

Kind regards
Marco

![image](https://user-images.githubusercontent.com/31255586/62029976-45031300-b1e4-11e9-95ca-c5dd66fccd61.png)
