### ISSUE TITLE
Translate SheetMetal WB

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_SheetMetal#99]
Relevant https://forum.freecadweb.org/viewtopic.php?f=10&t=36413

**Comment by luzpaz** [comment]
@ceremcem is this something you'd be able to assist with? We can'tfigure out how to enable translations in this repo

**Comment by luzpaz** [comment]
Ok, unbeknownst to me had a breakthrough and do posses the ability to translate external workbenches now, See https://forum.freecadweb.org/viewtopic.php?f=10&t=36413&start=20#p394615

**Comment by jaisekjames** [comment]
pls see pull request. 

https://github.com/shaise/FreeCAD_SheetMetal/pull/183

**Comment by ceremcem** [comment]
@luzpaz I'm sorry, I missed above mention :(

**Comment by luzpaz** [comment]
You rock @jaisekjames !  
No worries @ceremcem   
Closing ticket (see #183)
